name = "leonardchan-api"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "leonardchan-db"
database_id = "ec79a01e-8aef-4383-a9ba-c07f1129d5ec"

[[kv_namespaces]]
binding = "KV"
id = "498e3226d4354533b16289ed0967ecef"

[vars]
ENVIRONMENT = "production"
SITE_NAME = "Leonard Chan, MH"
SITE_URL = "https://www.leonardchan.com"
